name: Test MyCLI Setup

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: |
          cd ./.github/actions/my-cli-action
          npm install

      - name: Install MyCLI
        uses: ./.github/actions/my-cli-action
        with:
          version: '1.2.3'

      - name: Verify CLI Installation
        run: |
          echo "Checking MyCLI version..."
          mycli --version
